"""Initial

Revision ID: 3e1e0485ef25
Revises: 
Create Date: 2026-03-04 13:47:24.900879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e1e0485ef25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystem_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('ALMA', 'SKILL', 'TOOL', name='resource_type_enum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('alma_type', sa.Enum('THEORETICAL', 'METHODOLOGICAL', name='alma_type_enum'), nullable=True),
    sa.Column('scope', sa.Enum('LOCAL', 'GLOBAL', name='scope_enum'), nullable=True),
    sa.Column('origin_project_id', sa.UUID(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('personality_descriptor', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('academic_level', sa.Enum('HIGHSCHOOL', 'BACHELORS', 'MASTERS', 'PHD', name='academic_level_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('domain_area', sa.String(), nullable=False),
    sa.Column('academic_level', sa.Enum('HIGHSCHOOL', 'BACHELORS', 'MASTERS', 'PHD', name='academic_level_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'ANALYSIS', 'COMPLETE', name='project_status_enum'), nullable=True),
    sa.Column('human_guidelines', sa.Text(), nullable=True),
    sa.Column('theoretical_alma_id', sa.UUID(), nullable=True),
    sa.Column('methodological_alma_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['methodological_alma_id'], ['ecosystem_resources.id'], ),
    sa.ForeignKeyConstraint(['theoretical_alma_id'], ['ecosystem_resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ALMA', 'SYSTEM', name='role_enum'), nullable=False),
    sa.Column('alma_id', sa.UUID(), nullable=True),
    sa.Column('alma_name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.create_table('project_canvas_state',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('canvas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_canvas_state')
    op.drop_index(op.f('ix_chat_messages_project_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ecosystem_resources')
    # ### end Alembic commands ###
